# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:23.6.1-alpine
WORKDIR /app

# Copy package files first
COPY package*.json ./
COPY packages/server/package*.json ./packages/server/
COPY tsconfig.json ./

# Install dependencies at root level first
RUN npm install

# Copy source files
COPY . .

# Build the server package
RUN npm install && npm run build

EXPOSE 3000

# Start the server
CMD ["node", "dist/index.js"]
