# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:23.6.1-alpine
WORKDIR /app

# Copy package files first
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install
# Copy source files
COPY . .
# Install dependencies at root level first
RUN npm run build



# Build the server package


EXPOSE 3000

# Start the server
CMD ["node", "dist/index.js"]
